## Arewa DataScience Academy
### Deep Learning Cohort 1.0
#### WEEK 1 Exercises
#### Exercises:

In [1]:
import torch
tensor = torch.randn(7, 7)
print(tensor)

tensor([[-0.1963,  0.7019,  0.6113, -1.0962, -0.0336,  1.4641,  0.2738],
        [ 0.3523, -3.3408, -0.3324, -0.5706, -0.2205, -1.2945,  0.3024],
        [ 2.1478, -0.5705, -0.0615,  0.2535, -0.1590, -0.1550, -1.0820],
        [-0.9655, -1.3840, -0.9386,  1.4877, -0.8094,  0.2993,  0.9146],
        [ 0.1534,  0.2414, -0.5994, -0.3021,  0.3436, -1.5698,  1.2954],
        [-0.3688,  1.3234,  0.1971,  0.1479,  1.5832, -0.9524, -1.2891],
        [ 0.0059, -0.9011, -0.1103, -0.4078, -0.8185,  0.2593,  0.3742]])


In [2]:
import torch
# Create the first random tensor (shape: 7x7)
tensor1 = torch.randn(7, 7)
# Create the second random tensor and transpose it (shape: 1x7)
tensor2 = torch.randn(1, 7).t()
# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2)
print(result)

tensor([[ 2.4459],
        [ 4.5195],
        [ 1.4639],
        [ 0.2680],
        [-1.6168],
        [-1.5594],
        [ 0.3328]])


In [3]:
import torch
# Set the random seed to 0
torch.manual_seed(0)
# Create a random tensor with shape (7, 7)
tensor1 = torch.randn(7, 7)
print("Random Tensor 1:")
print(tensor1)
# Create a random tensor with shape (1, 7) and transpose it
tensor2 = torch.randn(1, 7).t()
print("Random Tensor 2:")
print(tensor2)
# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2)
print("Result:")
print(result)

Random Tensor 1:
tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160],
        [-2.1152,  0.3223, -1.2633,  0.3500,  0.3081,  0.1198,  1.2377],
        [ 1.1168, -0.2473, -1.3527, -1.6959,  0.5667,  0.7935,  0.5988],
        [-1.5551, -0.3414,  1.8530,  0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437, -0.6136,  0.8728,  1.0554],
        [ 0.1778, -0.2303, -0.3918,  0.5433, -0.3952,  0.2055,  0.7440],
        [ 1.5210,  3.4105, -1.5312, -1.2341,  1.8197, -0.5515, -1.3253]])
Random Tensor 2:
tensor([[-2.2858],
        [ 0.0700],
        [ 0.6674],
        [-1.0403],
        [-0.4820],
        [ 1.1293],
        [-1.1624]])
Result:
tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])


In [4]:
import torch
# Set the random seed for CPU operations
torch.manual_seed(0)
if torch.cuda.is_available():
    # Set the random seed for GPU operations
    torch.cuda.manual_seed(1234)

In [5]:
import torch
# Set the random seed for CPU operations
torch.manual_seed(1234)
if torch.cuda.is_available():
    # Set the random seed for GPU operations
    torch.cuda.manual_seed(0)
    # Create random tensors on the GPU
    tensor1 = torch.randn(2, 3).cuda()
    tensor2 = torch.randn(2, 3).cuda()
    # Print the tensors
    print("Tensor 1:")
    print(tensor1)
    print("Tensor 2:")
    print(tensor2)
else:
    print("GPU not available.")

GPU not available.


In [6]:
import torch
# Set the random seed for CPU operations
torch.manual_seed(1234)
if torch.cuda.is_available():
    # Set the random seed for GPU operations
    torch.cuda.manual_seed(0)
    # Create random tensors on the GPU
    tensor1 = torch.randn(2, 3).cuda()
    tensor2 = torch.randn(3, 2).cuda()
    # Perform matrix multiplication
    result = torch.matmul(tensor1, tensor2)
    # Print the result
    print("Result:")
    print(result)
else:
    print("GPU not available.")

GPU not available.


In [7]:
import torch
# Set the random seed for CPU operations
torch.manual_seed(1234)
if torch.cuda.is_available():
    # Set the random seed for GPU operations
    torch.cuda.manual_seed(0)
    # Create random tensors on the GPU
    tensor1 = torch.randn(2, 3).cuda()
    tensor2 = torch.randn(3, 2).cuda()
    # Perform matrix multiplication
    result = torch.matmul(tensor1, tensor2)
    # Find the maximum and minimum values
    max_value = torch.max(result)
    min_value = torch.min(result)

    # Print the maximum and minimum values
    print("Maximum value:", max_value.item())
    print("Minimum value:", min_value.item())
else:
    print("GPU not available.")


GPU not available.


In [ ]:
import torch
# Set the random seed for CPU operations
torch.manual_seed(1234)
if torch.cuda.is_available():
    # Set the random seed for GPU operations
    torch.cuda.manual_seed(0)
    # Create random tensors on the GPU
    tensor1 = torch.randn(2, 3).cuda()
    tensor2 = torch.randn(3, 2).cuda()
    # Perform matrix multiplication
    result = torch.matmul(tensor1, tensor2)
    # Find the maximum and minimum index values
    max_value, max_index = torch.max(result, dim=1)
    min_value, min_index = torch.min(result, dim=1)
    # Print the maximum and minimum index values
    print("Maximum index:", max_index.item())
    print("Minimum index:", min_index.item())
else:
    print("GPU not available.")


In [8]:
import torch
# Set the random seed
torch.manual_seed(7)
# Create a random tensor with shape (1, 1, 1, 10)
tensor1 = torch.randn(1, 1, 1, 10)
print("Original Tensor:")
print(tensor1)
print("Original Tensor Shape:", tensor1.shape)
# Remove the '1' dimensions
tensor2 = tensor1.squeeze()
print("Modified Tensor:")
print(tensor2)
print("Modified Tensor Shape:", tensor2.shape)

Original Tensor:
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Original Tensor Shape: torch.Size([1, 1, 1, 10])
Modified Tensor:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
Modified Tensor Shape: torch.Size([10])
